### ISSUE TITLE
Black screen after booting. Not sleeping after closing the lid. Mouse and trackpad lag and self-moving.

### ISSUE THREAD

**Issue by Welpit69** [kidonng/HP-Pavilion-13-Hackintosh#3]
Hi, 

1. After using your EFI file to boot my macOS, it works very good. however, the only issue is that after choosing the macOS boot entry and wait for the progress bar to advance to around half, the screen turns black with no backlight on (I used a flashlight to see, it's pure black). However, after around 2 minutes, the screen lights up and my inputs on the keyboard and mouse do work (using spotlight and choosing a folder to open). 

2. Closing the lid of the laptop makes the screen to turn black but the laptop does not go into sleep (by knowing that my keyboard's light is still on). Can this be fixed by adding "SMCLightSensor" kext into the EFI folder? 

3.  For around first 20 minutes booting into macOS, the mouse and trackpad experience lag and self-moving followed by the lag every 20-30 seconds. However, after the 20 minutes period, everything is fine.

I am using macOS Ventura 13.6.3 on Pavilion 13 an0060tu (should be same as yours except for the internal drive storage) with OpenCore 0.9.5 and bios F.12.

Thank you.

**Comment by kidonng** [comment]
1. This has been discussed privately
2. SMCLightSensor should have nothing to do with the issue since it is ["used for the ambient light sensor on laptops"](https://dortania.github.io/OpenCore-Install-Guide/ktext.html#virtualsmc-plugins)
3. I have only used hackintosh with a Bluetooth mouse and have not encountered similar issues.
